import type { ProductCardProduct, ProductCardVariant } from './types'

/**
 * Story-only fixtures for the ProductCard family (not part of the public API). Mirror the legacy
 * `dummy-product.ts` products (El Esteco Malbec, Norrlands Guld) but in the V2 `ProductCardProduct`
 * shape, with the translation labels filled in so the Visual stories render clean, representative
 * frames (the legacy story mappers left them undefined, printing "undefined:" in the price line).
 */

const wineVariants: ProductCardVariant[] = [
  {
    productName: 'El Esteco Malbec',
    variantName: '75cl Engångsglas',
    variantId: '2543824',
    priceStr: '136',
    country: 'Argentina',
    price: 136,
    pricePerUnit: 136,
    pricePerUnitString: '136',
    salesUnit: 'ST',
    itemNumberPerSalesUnit: 1,
    sellerOnly: true,
    image: { id: 'variant-2543824', src: '', sources: [] },
  },
  {
    productName: 'El Esteco Malbec',
    variantName: '75cl Kolli',
    variantId: '2543814',
    priceStr: '136',
    country: 'Argentina',
    price: 136,
    pricePerUnit: 136,
    pricePerUnitString: '136',
    salesUnit: 'KLI',
    itemNumberPerSalesUnit: 6,
    sellerOnly: false,
    image: { id: 'variant-2543814', src: '', sources: [] },
  },
]

export const dummyWineProduct: ProductCardProduct = {
  partNo: '2543824',
  productName: 'El Esteco Malbec',
  productUrl: '/Product/2543824',
  primaryImageUrl: 'https://spendrups.cdn.storm.io/b2ded0dd-7eb5-4983-9d91-24b948468246',
  country: 'Argentina',
  packaging: '75cl Engångsglas',
  price: 136,
  priceStr: '136',
  pricePerUnit: 136,
  pricePerUnitString: '136',
  salesUnit: 'ST',
  itemNumberPerSalesUnit: 1,
  quantity: '1',
  totalPrice: '136,00',
  tags: [
    { text: 'Eko', color: 'green' },
    { text: 'Fairtrade', color: 'blue' },
    { text: 'Vegan', color: 'purple' },
  ],
  productVariantList: wineVariants,
  partNoLabel: 'Art.nr.',
  unitLabel: 'st',
  currencyLabel: 'kr',
  priceLabel: 'Pris',
  aLabel: 'à',
}

export const dummyProductNoVariants: ProductCardProduct = {
  partNo: '1105101',
  productName: 'Norrlands Guld Export 5,3',
  productUrl: '/Product/1105101',
  primaryImageUrl: 'https://spendrups.cdn.storm.io/4237ad51-a9f9-45e5-a85a-72389f6e65bb',
  country: 'Sverige',
  packaging: '50cl Returglas',
  price: 22.677,
  priceStr: '22,68',
  pricePerUnit: 22.677,
  pricePerUnitString: '22,68',
  salesUnit: 'KLI',
  itemNumberPerSalesUnit: 15,
  quantity: '1',
  totalPrice: '340,16',
  tags: [],
  productVariantList: [
    {
      productName: 'Norrlands Guld Export 5,3',
      variantName: '50cl Returglas',
      variantId: '1105101',
      priceStr: '22,68',
      country: 'Sverige',
      price: 22.677,
      pricePerUnit: 22.677,
      pricePerUnitString: '22,68',
      salesUnit: 'KLI',
      itemNumberPerSalesUnit: 15,
      sellerOnly: false,
      image: { id: 'variant-1105101', src: '', sources: [] },
    },
  ],
  partNoLabel: 'Art.nr.',
  unitLabel: 'kolli',
  currencyLabel: 'kr',
  priceLabel: 'Pris',
  aLabel: 'à',
}

export const dummyBeerProduct: ProductCardProduct = {
  partNo: '1125111',
  productName: 'Norrlands Guld',
  productUrl: '/Product/1125111',
  primaryImageUrl: 'https://spendrups.cdn.storm.io/4237ad51-a9f9-45e5-a85a-72389f6e65bb',
  country: 'Sweden',
  packaging: '33cl Engångsglas',
  price: 1,
  priceStr: '1',
  pricePerUnit: 1,
  pricePerUnitString: '1',
  salesUnit: 'st',
  itemNumberPerSalesUnit: 1,
  quantity: '1',
  totalPrice: '1,00',
  tags: [{ text: 'Nyhet', color: 'purple' }],
  productVariantList: [
    {
      productName: 'Norrlands Guld',
      variantName: '33cl Engångsglas',
      variantId: '1125111',
      priceStr: '1',
      country: 'Sweden',
      price: 1,
      pricePerUnit: 1,
      pricePerUnitString: '1',
      salesUnit: 'st',
      itemNumberPerSalesUnit: 24,
      sellerOnly: false,
      image: { id: 'variant-1125111', src: '', sources: [] },
    },
    {
      productName: 'Norrlands Guld',
      variantName: '30l FAT',
      variantId: '1125141',
      priceStr: '1',
      country: 'Sweden',
      price: 1,
      pricePerUnit: 1,
      pricePerUnitString: '1',
      salesUnit: 'Kolli',
      itemNumberPerSalesUnit: 1,
      sellerOnly: false,
      image: { id: 'variant-1125141', src: '', sources: [] },
    },
  ],
  partNoLabel: 'Art.nr.',
  unitLabel: 'kolli',
  currencyLabel: 'kr',
  priceLabel: 'Pris',
  aLabel: 'à',
}
