import type { Meta, StoryObj } from '@storybook/react-vite'
import { expect, within } from 'storybook/test'
import type { ReactNode } from 'react'
import {
  fontFamilies,
  fontWeights,
  trackings,
  typographyGroups,
  typeTokenCount,
  type FontFamily,
  type TypeGroup,
  type TypeToken,
} from './theme-typography'

/**
 * Live typography reference. Font families, the size scale (with paired
 * line-heights) and letter-spacing are parsed from the `@theme` tokens in
 * `src/styles/index.css` (see `theme-typography.ts`), so this page stays in
 * sync with the theme automatically.
 *
 * Samples are rendered with inline `var(--token)` references rather than
 * `text-*` utility classes: the token names are dynamic, so utility classes
 * can't be statically generated by Tailwind — but the `@theme` custom
 * properties are emitted to `:root`, so the variables resolve at runtime.
 */

const SPECIMEN = 'AaBbCcDd 0123456789'
const PANGRAM = 'Flygande bäckasiner söka hwila på mjuka tuvor.'
const SAMPLE = 'The quick brown fox jumps over the lazy dog'

/** Shared row: a single-line specimen on the left, aligned specs on the right. */
function SpecimenRow({ specimen, name, specs }: { specimen: ReactNode; name: string; specs: ReactNode[] }) {
  return (
    <div className="flex items-baseline justify-between gap-6 border-b border-grey-300 py-4 last:border-b-0">
      <div className="min-w-0 flex-1 truncate">{specimen}</div>
      <div className="w-40 shrink-0 text-right font-secondary">
        <div className="text-sm font-bold text-text-default">{name}</div>
        {specs.map((line, i) => (
          <div key={i} className="text-xs text-text-subdued">
            {line}
          </div>
        ))}
      </div>
    </div>
  )
}

function Section({
  title,
  description,
  children,
}: {
  title: string
  description: ReactNode
  children: ReactNode
}) {
  return (
    <section className="flex flex-col gap-6">
      <div className="flex flex-col gap-1">
        <h2 className="text-h-s font-bold text-text-default">{title}</h2>
        <p className="max-w-content-text text-body text-text-subdued">{description}</p>
      </div>
      {children}
    </section>
  )
}

function FontFamilyCard({ family }: { family: FontFamily }) {
  return (
    <article className="flex flex-col gap-5 rounded-lg border border-grey-300 p-6">
      <div className="flex flex-col gap-1">
        <h3 className="text-h-xs font-bold text-text-default">{family.name}</h3>
        <code className="font-secondary text-xs break-words text-text-subdued">{family.value}</code>
      </div>
      <p className="text-h-l leading-tight text-text-default" style={{ fontFamily: `var(${family.cssVar})` }}>
        {SPECIMEN}
      </p>
      <div
        className="flex flex-col gap-2 border-t border-grey-300 pt-4"
        style={{ fontFamily: `var(${family.cssVar})` }}
      >
        <p className="text-body text-text-default">
          <span className="font-secondary text-xs text-text-subdued">Regular · 400</span>
          <br />
          {PANGRAM}
        </p>
        {fontWeights.map((weight) => (
          <p key={weight.cssVar} className="text-body text-text-default" style={{ fontWeight: `var(${weight.cssVar})` }}>
            <span className="font-secondary text-xs font-normal text-text-subdued">
              {weight.name} · {weight.value}
            </span>
            <br />
            {PANGRAM}
          </p>
        ))}
      </div>
    </article>
  )
}

function TypeScaleGroup({ group }: { group: TypeGroup }) {
  return (
    <section className="flex flex-col gap-2">
      <h3 className="text-xs font-bold tracking-wide text-text-subdued uppercase">{group.name}</h3>
      <div className="flex flex-col">
        {group.tokens.map((token) => (
          <TypeRow key={token.cssVar} token={token} />
        ))}
      </div>
    </section>
  )
}

function TypeRow({ token }: { token: TypeToken }) {
  const specs = [
    `${token.size}${token.sizePx ? ` · ${token.sizePx}` : ''}`,
    ...(token.lineHeight ? [`line-height ${token.lineHeight}`] : []),
  ]
  return (
    <SpecimenRow
      name={token.name}
      specs={specs}
      specimen={
        <p
          className="truncate font-primary text-text-default"
          style={{
            fontSize: `var(${token.cssVar})`,
            ...(token.lineHeightVar ? { lineHeight: `var(${token.lineHeightVar})` } : {}),
          }}
        >
          {SAMPLE}
        </p>
      }
    />
  )
}

function LetterSpacingSection() {
  if (trackings.length === 0) return null
  return (
    <Section title="Letter Spacing" description="Tracking tokens, applied to CTA labels.">
      <div className="flex flex-col">
        {trackings.map((tracking) => (
          <SpecimenRow
            key={tracking.cssVar}
            name={tracking.name}
            specs={[tracking.value]}
            specimen={
              <p
                className="truncate text-cta-l font-bold text-text-default uppercase"
                style={{ letterSpacing: `var(${tracking.cssVar})` }}
              >
                Add to cart
              </p>
            }
          />
        ))}
      </div>
    </Section>
  )
}

function FontFamiliesSection() {
  return (
    <Section
      title="Font Families"
      description={
        <>
          {fontFamilies.length} families. The document defaults to{' '}
          <code className="font-secondary">font-primary</code>; opt into others per component.
        </>
      }
    >
      <div className="grid gap-6 lg:grid-cols-2">
        {fontFamilies.map((family) => (
          <FontFamilyCard key={family.cssVar} family={family} />
        ))}
      </div>
    </Section>
  )
}

function TypeScaleSection() {
  return (
    <Section
      title="Type Scale"
      description={
        <>
          {typeTokenCount} size tokens, each paired with its line-height. Applied with the{' '}
          <code className="font-secondary">text-*</code> utilities.
        </>
      }
    >
      <div className="flex flex-col gap-10">
        {typographyGroups.map((group) => (
          <TypeScaleGroup key={group.name} group={group} />
        ))}
      </div>
    </Section>
  )
}

function TypographyPage({ children }: { children: ReactNode }) {
  return (
    <main className="bg-white font-primary text-text-default">
      <div className="mx-auto flex w-full max-w-content-md flex-col gap-14 px-6 py-10">
        <header className="flex flex-col gap-2">
          <h1 className="text-h-m font-bold">Typography</h1>
          <p className="max-w-content-text text-body text-text-subdued">
            Font families, the type scale and letter-spacing — extracted live from the Tailwind
            theme in <code className="font-secondary">src/styles/index.css</code>.
          </p>
        </header>
        {children}
      </div>
    </main>
  )
}

const meta = {
  title: 'Design System/Foundations/Typography',
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'Central overview of the design system typography, generated dynamically from the Tailwind v4 `@theme` font, size and tracking tokens.',
      },
    },
  },
} satisfies Meta

export default meta
type Story = StoryObj<typeof meta>

/** Everything — families, type scale and letter-spacing. */
export const Overview: Story = {
  render: () => (
    <TypographyPage>
      <FontFamiliesSection />
      <TypeScaleSection />
      <LetterSpacingSection />
    </TypographyPage>
  ),
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement)

    await expect(canvas.getByRole('heading', { level: 1, name: 'Typography' })).toBeInTheDocument()
    await expect(canvas.getByRole('heading', { name: 'Font Families' })).toBeInTheDocument()
    await expect(canvas.getByRole('heading', { name: 'Type Scale' })).toBeInTheDocument()

    // Family + a foundational size token render from the parsed theme.
    await expect(canvas.getAllByText('font-primary').length).toBeGreaterThan(0)
    await expect(canvas.getByRole('heading', { name: /headings — mobile/i })).toBeInTheDocument()
    await expect(canvas.getAllByText('h-xl').length).toBeGreaterThan(0)
    await expect(canvas.getAllByText(/2\.5rem · 40px/).length).toBeGreaterThan(0)
  },
}

/** Just the font families and their weights. */
export const FontFamilies: Story = {
  render: () => (
    <TypographyPage>
      <FontFamiliesSection />
    </TypographyPage>
  ),
}

/** Just the type scale. */
export const TypeScale: Story = {
  render: () => (
    <TypographyPage>
      <TypeScaleSection />
    </TypographyPage>
  ),
}
